[main]
font=SauceCodePro Nerd Font Mono:size=14

# VS Code Light theme: https://github.com/Mofiqul/vscode.nvim/blob/main/extra/foot/vscode-light

initial-color-theme=light

[colors-light]
alpha=1.00
background=ffffff
foreground=000000

regular0=000000
regular1=c7230f
regular2=008000
regular3=795e25
regular4=007acc
regular5=af00db
regular6=3a8f99
regular7=000000

bright0=000000
bright1=c7230f
bright2=008000
bright3=795e25
bright4=007acc
bright5=af00db
bright6=3a8f99
bright7=000000
